src/objects/CompensationRate__c.object
<CustomObject>
    <description>Various rates to reimburse dependant expense types e.g. travels with private vehicles etc.</description>
    <fields>
        <fullName>cur_FullDailyRate__c</fullName>
        <label>Full Daily Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>cur_PartialDailyRate__c</fullName>
        <label>Partial Daily Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>pct_FullDayAllowanceRate__c</fullName>
        <inlineHelpText>For more than 8 hours absence.</inlineHelpText>
        <label>Full Day Allowance Rate</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Compensation Rate</label>
    <nameField>
        <label>Compensation Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compensation Rates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Expense__c.object
<CustomObject>
    <description>Contains informations about the expenses.</description>
    <fields>
        <fullName>cur_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Overall cost of the expense.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>cur_Deduction__c</fullName>
        <label>Deduction</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>cur_OriginalAmount__c</fullName>
        <label>Original Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>dat_ExpenseDate__c</fullName>
        <description>To assign a Expense to a specific travel date.</description>
        <label>Expense Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dtm_ArrivalTime__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_Begin__c</fullName>
        <label>Begin</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_DepartureTime__c</fullName>
        <label>Departure Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_End__c</fullName>
        <label>End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>lkp_LocationFrom__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location From</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a location.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Expenses (Location From)</relationshipLabel>
        <relationshipName>Expenses2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>lkp_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a location.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>lkp_MealInvitation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meal Invitation</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>MealInvitation__c.mdr_Travel__c</field>
                <operation>equals</operation>
                <valueField>$Source.mdr_Travel__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MealInvitation__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>mdr_Travel__c</fullName>
        <label>Travel</label>
        <referenceTo>Travel__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>pkl_Reimbursement__c</fullName>
        <label>Reimbursement</label>
        <picklist>
            <picklistValues>
                <fullName>I paid for this, please reimburse me.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The company paid for this.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The customer paid for this.</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Expense #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <recordTypes>
        <fullName>perDiem</fullName>
        <active>true</active>
        <description>auto-generated Expense records for calculating the per diem allowance</description>
        <label>per Diem</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LongDistanceRide__c.object
<CustomObject>
    <fields>
        <fullName>dtm_ArrivalTime__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_DepartureTime__c</fullName>
        <label>Departure Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>lkp_LocationFrom__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location From</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This is not a Location.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Long Distance Rides</relationshipLabel>
        <relationshipName>Long_Distance_Rides</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>lkp_LocationTo__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location To</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This is not a Location.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Long Distance Rides (Location To)</relationshipLabel>
        <relationshipName>Long_Distance_Rides1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>mdr_RentalVehicle__c</fullName>
        <label>Rental Vehicle</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This is not a Rental Vehicle expense.</errorMessage>
            <filterItems>
                <field>Expense__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Rental Vehicle</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Long Distance Rides</relationshipLabel>
        <relationshipName>Long_Distance_Rides</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Long Distance Ride</label>
    <nameField>
        <displayFormat>LDR-{0000}</displayFormat>
        <label>Long Distance Ride #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Long Distance Rides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MealInvitation__c.object
<CustomObject>
    <fields>
        <fullName>dat_Day__c</fullName>
        <label>Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>lkp_Breakfast__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Breakfast</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a Meal.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Meal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Meal Invitations</relationshipLabel>
        <relationshipName>Meal_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>lkp_Dinner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Dinner</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a meal.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Meal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Meal Invitations (Dinner)</relationshipLabel>
        <relationshipName>Meal_Invitations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>lkp_Lunch__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Lunch</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a meal.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Meal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Meal Invitations (Lunch)</relationshipLabel>
        <relationshipName>Meal_Invitations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>mdr_Travel__c</fullName>
        <label>Travel</label>
        <referenceTo>Travel__c</referenceTo>
        <relationshipLabel>Meal Invitations</relationshipLabel>
        <relationshipName>MealInvitations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Meal Invitation</label>
    <nameField>
        <displayFormat>MI-{0000}</displayFormat>
        <label>Meal Invitation #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meal Invitations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Travel__c.object
<CustomObject>
    <description>Records of business travels.</description>
    <fields>
        <fullName>dtm_End__c</fullName>
        <label>End</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_Start__c</fullName>
        <label>Start</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Travel</label>
    <nameField>
        <label>Travel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PerDiemCalculator.cls
public with sharing class PerDiemCalculator {
    
    private  Travel__c travel;
    private CompensationRate__c currentLocation; 
    
    private List<Expense__c> movementExpenses;
    private List<Expense__c> accommodationExpenses;
    private List<Expense__c> oldPerDiems;
    
    private Map<Id,CompensationRate__c> locations;
    private Map<Date,MealInvitation__c> mealInvitations;
    
    
    // CONSTRUCTOR
    
    public PerDiemCalculator(Travel__c travel) {
    	this.travel = travel;
 		initExpenses();
 		initLocations();
 		initMealInvitations();
    }
    
    
    // PUBLIC METHODS
    
    public void calculate() {
    	List<Expense__c> newPerDiems = new List<Expense__c>();
        
        delete oldPerDiems;
        
        try {
	    	if(isShorterOrEqualEightHours()) {
	    		newPerDiems.add(generateShortTravelPerDiem());
	    	}
	    	else {
	    		if(isOvernightTravel()) {
					newPerDiems.add(generateOverNightPerDiem());
	    		}
	    		else {
	    			newPerDiems.addAll(generatePerDiems());
	    		}
	    	}
	    	
	    	insert newPerDiems;
    	}
    	catch(Exception ignore) {}
    }
    
    
	// PRIVATE METHODS
	
	private void initExpenses() {
		movementExpenses = new List<Expense__c>();
		accommodationExpenses = new List<Expense__c>();
		oldPerDiems = new List<Expense__c>();
		
		Set<Id> recordTypes = new Set<Id>();
		recordTypes.add(ExpenseType.getEntertainmentRecordTypeId());
		recordTypes.add(ExpenseType.getMiscellaneousRecordTypeId());
		
		for(Expense__c expense : [SELECT RecordTypeId, dtm_ArrivalTime__c, dtm_DepartureTime__c,lkp_Location__c, lkp_LocationFrom__c,
    					   				 (SELECT dtm_DepartureTime__c, dtm_ArrivalTime__c,lkp_LocationFrom__c,lkp_LocationTo__c
    					   			   	  FROM Long_Distance_Rides__r)	
    							  FROM Expense__c 
    							  WHERE mdr_travel__c = :travel.id
    							  AND RecordTypeId NOT IN :recordTypes]) {
    		
    		if(ExpenseType.isMovement(expense)) {
    			movementExpenses.add(expense);
    		}					  	
			else if(ExpenseType.isAccommodation(expense)) {
				accommodationExpenses.add(expense);
			}
			else if(ExpenseType.isPerDiem(expense)) {
				oldPerDiems.add(expense);
			}
			else if(ExpenseType.isRentalVehicle(expense)) {
				for(LongDistanceRide__c ldr : expense.Long_Distance_Rides__r) {
					Expense__c falseExpense = new Expense__c();
					
		    		falseExpense.dtm_DepartureTime__c = ldr.dtm_DepartureTime__c;
		    		falseExpense.dtm_ArrivalTime__c = ldr.dtm_ArrivalTime__c;
		    		falseExpense.lkp_LocationFrom__c = ldr.lkp_LocationFrom__c;
		    		falseExpense.lkp_Location__c = ldr.lkp_LocationTo__c;
		    		
		    		movementExpenses.add(falseExpense);
				}
			}
		}
	}
	
	
	private void initLocations() {
		locations = new Map<Id,CompensationRate__c>([SELECT Id, CurrencyIsoCode,cur_FullDailyRate__c, cur_PartialDailyRate__c
												     FROM CompensationRate__c
												     WHERE RecordTypeId = :CompensationRateType.getLocationId()]);
	}
	
	
	private void initMealInvitations() {
    	mealInvitations = new Map<Date,MealInvitation__c>();
    	
    	for(MealInvitation__c invitation : [SELECT Id, dat_Day__c, lkp_Breakfast__c, 
    											   lkp_Breakfast__r.pct_FullDayAllowanceRate__c,
    									   		   lkp_Lunch__c, lkp_Lunch__r.pct_FullDayAllowanceRate__c,
    									   		   lkp_Dinner__c, lkp_Dinner__r.pct_FullDayAllowanceRate__c
    										FROM MealInvitation__c
    										WHERE mdr_Travel__c = :travel.Id]) {
    		mealInvitations.put(invitation.dat_Day__c,invitation);
    	}
	}
    
    
    // CHECKING METHODS
    
    private Boolean isShorterOrEqualEightHours() {
    	Long dt1 = travel.dtm_End__c.getTime();  
   		Long dt2 = travel.dtm_Start__c.getTime();
   		
   		Double difference = dt1 - dt2;
   		difference = difference/ 1000 / 60 / 60;
    	
    	Boolean result = (difference <= 8);
    	
    	return result;
    }
    
        
    private Boolean isOvernightTravel() {
    	Integer travelDuration = travel.dtm_End__c.day() - travel.dtm_Start__c.day();
    	
    	Boolean result = (travelDuration == 1) && (accommodationExpenses.isEmpty());
    	
    	return result;
    }
    
    
    // PER DIEM GENERATING METHODS
    
    private Expense__c generateShortTravelPerDiem() {
    	Date travelFirstDay = travel.dtm_Start__c.date();
    	Date travelLastDay = travel.dtm_End__c.date();
    	
    	determineLocationOfTheDay(travelFirstDay,travelLastDay);
   		
    	Expense__c result = createDefaultPerDiem(travelFirstDay);
    	
		result.cur_Amount__c = 0.00;
   		result.cur_OriginalAmount__c = 0.00;
   		result.cur_Deduction__c = 0.00;
   		result.dtm_Begin__c = travel.dtm_Start__c;
   		result.dtm_End__c = travel.dtm_End__c;
   		result.lkp_Location__c = currentLocation.Id;
   		result.CurrencyIsoCode = currentLocation.CurrencyIsoCode;
    	result.lkp_MealInvitation__c = findMealInvitation(travelFirstDay);
    	    	
    	return result;
    }
    
    
    private Expense__c generateOverNightPerDiem() {
    	Date travelFirstDay = travel.dtm_Start__c.date();
    	Date travelLastDay = travel.dtm_End__c.date();
    	
   		determineLocationOfTheDay(travelFirstDay, travelLastDay);
   		
    	Expense__c result = createDefaultPerDiem(travelFirstDay);
    	
   		result.dtm_Begin__c = travel.dtm_Start__c;
   		result.dtm_End__c = travel.dtm_End__c;
   		result.lkp_Location__c = currentLocation.Id;
   		result.CurrencyIsoCode = currentLocation.CurrencyIsoCode;
   		result.cur_OriginalAmount__c = currentLocation.cur_PartialDailyRate__c;
		result.cur_Deduction__c = calculateMealDeduction(travelFirstDay, true);
   		
   		Id mealInvitation = findMealInvitation(travelFirstDay);
   		if(mealInvitation == null) {
   			mealInvitation = findMealInvitation(travelLastDay);
   		}
   		result.lkp_MealInvitation__c = mealInvitation;
 		
   		Decimal amount = result.cur_OriginalAmount__c - result.cur_Deduction__c;
        if(amount < 0) {
            amount = 0;
        }
   		result.cur_Amount__c = amount;
   		 
   		return result;    			
    }
    	
    
    private List<Expense__c> generatePerDiems() {
    	Date travelFirstDay = travel.dtm_Start__c.date();
    	Date travelLastDay = travel.dtm_End__c.date();
    	
    	List<Expense__c> results = new List<Expense__c>();

		for( Date day = travelFirstDay ; day <= travelLastDay ; day = day.addDays(1)) {
            Expense__c perDiem = createDefaultPerDiem(day);
            
        	determineLocationOfTheDay(travelFirstDay, travelLastDay, day);
                        	
            if (day.isSameDay(travelFirstDay)) {
            	perDiem.dtm_Begin__c = travel.dtm_Start__c;
                perDiem.dtm_End__c = DateTime.newInstance(day,Time.newInstance(23,59,59,00));
                perDiem.cur_OriginalAmount__c = currentLocation.cur_PartialDailyRate__c;
            }
            else if(day.isSameDay(travelLastDay)) {
                perDiem.dtm_Begin__c = DateTime.newInstance(day,Time.newInstance(00,00,00,00));
                perDiem.dtm_End__c = travel.dtm_End__c;
                perDiem.cur_OriginalAmount__c = currentLocation.cur_PartialDailyRate__c;
            }
            else {
                perDiem.dtm_Begin__c = DateTime.newInstance(day,Time.newInstance(00,00,00,00));
                perDiem.dtm_End__c = DateTime.newInstance(day,Time.newInstance(23,59,59,00));
                perDiem.cur_OriginalAmount__c = currentLocation.cur_FullDailyRate__c;
            }
            
            perDiem.lkp_Location__c = currentLocation.Id;
	        perDiem.CurrencyIsoCode = currentLocation.CurrencyIsoCode;
	        perDiem.cur_Deduction__c = calculateMealDeduction(day,false);
            perDiem.lkp_MealInvitation__c = findMealInvitation(day);
 
			Decimal amount = perDiem.cur_OriginalAmount__c - perDiem.cur_Deduction__c;
	        if(amount < 0) {
	            amount = 0;
	        }
	   		perDiem.cur_Amount__c = amount;
            
            results.add(perDiem);
        }
        
        return results;
    }
	
	
	// CALCULATING AND DETERMINING METHODS
	
	private Expense__c createDefaultPerDiem(Date day) {
		Expense__c result = new Expense__c();
		
		result.mdr_Travel__c = travel.Id;
		result.RecordTypeId = ExpenseType.getPerDiemRecordTypeId();
		result.pkl_Reimbursement__c = 'I paid for this, please reimburse me.';
		result.dat_ExpenseDate__c = day;
		
		return result;
	}
	
	
	private Decimal calculateMealDeduction(Date day,Boolean overnight) {
		Double allowanceRate;
		
		if(overnight) {
			allowanceRate = calculateAllowanceRate(day) + calculateAllowanceRate(day.addDays(1));
		}
		else {
			allowanceRate = calculateAllowanceRate(day);
		}
		
		if(allowanceRate > 1) {
				allowanceRate = 1;
		}
		
		Decimal result = locations.get(currentLocation.Id).cur_FullDailyRate__c * allowanceRate;
				
		return result;
	}
	
	
	private Double calculateAllowanceRate(Date day) {
		Double result = 0.00;
		MealInvitation__c invitation = mealInvitations.get(day);
		
		if(invitation != null) {
			
			if(invitation.lkp_Breakfast__c != null) {
				result = result+ invitation.lkp_Breakfast__r.pct_FullDayAllowanceRate__c;
			}
			if(invitation.lkp_Lunch__c != null) {
				result = result+ invitation.lkp_Lunch__r.pct_FullDayAllowanceRate__c;
			}
			if(invitation.lkp_Dinner__c != null) {
				result = result+ invitation.lkp_Dinner__r.pct_FullDayAllowanceRate__c;
			}
		}
		
		return result/100;
	}
		
	
	private void determineLocationOfTheDay(Date firstDay, Date lastDay) {
		Expense__c movementOfTheDay;
		
		if(firstDay.isSameDay(lastDay)) {
			movementOfTheDay = determineLastExpensePerDay(firstDay);
		}
		else if(isOvernightTravel()) {
			movementOfTheDay = determineLastExpensePerDay(lastDay);
			
			if(movementOfTheDay == null) {
				movementOfTheDay = determineLastExpensePerDay(firstDay);
			}
		}
		
		if(movementOfTheDay != null) {
			currentLocation = locations.get(movementOfTheDay.lkp_LocationFrom__c);
		}
	}
		
	
	private void determineLocationOfTheDay(Date firstDay, Date lastDay, Date day) {
		Expense__c movementOfTheDay;
		
		if(firstDay.isSameDay(lastDay)) {
			movementOfTheDay = determineLastExpensePerDay(firstDay);
		
			if(movementOfTheDay != null) {
				currentLocation = locations.get(movementOfTheDay.lkp_LocationFrom__c);
			}
		}
		else {
			if(day.isSameDay(lastDay)) {
				movementOfTheDay = determineFirstExpensePerDay(day);
				
				if(movementOfTheDay != null) {
					currentLocation = locations.get(movementOfTheDay.lkp_LocationFrom__c);
				}
			}
			else {
				movementOfTheDay = determineLastExpensePerDay(day);
				
				if(day.IsSameDay(FirstDay) && movementOfTheDay == null) {
					movementOfTheDay = determineFirstExpensePerDay(day);
				}
				
				if(movementOfTheDay != null) {
					currentLocation = locations.get(movementOfTheDay.lkp_Location__c);
				}
			}
		}
	} 
	
	
	private Expense__c determineFirstExpensePerDay(Date day) {
		Expense__c result;
		DateTime compareTime = DateTime.newInstance(day,Time.newInstance(23,59,59,00));
		
		 for(Expense__c expense : movementExpenses) {
		 	DateTime departureTime = expense.dtm_DepartureTime__c;
		 	
		 	if( (departureTime.date() == day) && (departureTime < compareTime) ) {
	        	compareTime = departureTime;
	            result = expense;
		 	}
		 }
		 
		 return result;
	}


	private Expense__c determineLastExpensePerDay(Date day) {
		Expense__c result;
		DateTime compareTime = DateTime.newInstance(day,Time.newInstance(00,00,00,00));
		
		 for(Expense__c expense : movementExpenses) {
		 	DateTime arrivalTime = expense.dtm_ArrivalTime__c;
		 	
	 		if( (arrivalTime.date() == day) && (arrivalTime > compareTime) ) {
	        	compareTime = arrivalTime;
	            result = expense;
	    	}
		 }
		 
		 return result;
	}
	
	
    private Id findMealInvitation(Date day) {
    	Id result;
    	
		MealInvitation__c invitation = mealInvitations.get(day);
		
		if(invitation != null) {
			result = invitation.Id;
		}
		
		return result;
	}
}