src/objects/CompensationRate__c.object
<CustomObject>
    <description>Various rates to reimburse dependant expense types e.g. travels with private vehicles etc.</description>
    <fields>
        <fullName>cur_FullDailyRate__c</fullName>
        <label>Full Daily Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>cur_OvernightStayRate__c</fullName>
        <label>Overnight Stay Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>cur_PartialDailyRate__c</fullName>
        <label>Partial Daily Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>txt_CityName__c</fullName>
        <inlineHelpText>Only enter a city if there are special rates for this specific city.</inlineHelpText>
        <label>City Name (optional)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>txt_CountryCode__c</fullName>
        <description>The Country Code of the Country using the ISO 3166-1 alpha-2 Code.</description>
        <inlineHelpText>Enter the &quot;ISO 2 Letter Country Code&quot; for this country.</inlineHelpText>
        <label>Country Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>txt_CountryName__c</fullName>
        <label>Country Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Compensation Rate</label>
    <nameField>
        <label>Compensation Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compensation Rates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LocationFinder_Test.cls
@isTest
private class LocationFinder_Test {
	
	static {
		CustomSettings.addDefault();
	}


	@isTest
	private static void succeedsWhenCorrectLocationIsReturned() {
		// Setup
		CompensationRate__c existingLocation1 = insertLocation('Deutschland(Stuttgart)', 'Deutschland','Stuttgart', 'DE');
		CompensationRate__c existingLocation2 = insertLocation('Deutschland(Other)', 'Deutschland', 'Other', 'DE');
		CompensationRate__c existingLocation3 = insertLocation('Afghanistan', 'Afghanistan', null, 'AF');
		CompensationRate__c existingLocation4 = insertLocation('Frankreich', 'Frankreich', null, 'FA');
		
		String inputCity = 'Kabul';
		String inputCountry = 'AF';
		
		
		// Exercise
		Id resultLocationId = LocationFinder.findLocation(inputCity,inputCountry);

		
		// Verify
		System.assertEquals(existingLocation3.id, resultLocationId);
	}
	
	
	@isTest
	private static void succeedsWhenCorrectLocationIsReturnedForMultipleSameCountryLocations() {
		// Setup
		CompensationRate__c existingLocation1 = insertLocation('Deutschland(Stuttgart)', 'Deutschland','Stuttgart', 'DE');
		CompensationRate__c existingLocation2 = insertLocation('Deutschland(Other)', 'Deutschland', 'Other', 'DE');
		CompensationRate__c existingLocation3 = insertLocation('Afghanistan', 'Afghanistan', null, 'AF');
		CompensationRate__c existingLocation4 = insertLocation('Frankreich', 'Frankreich', null, 'FA');
		CompensationRate__c existingLocation5 = insertLocation('Deutschland(M?nchen)', 'Deutschland', 'M?nchen', 'DE');
		
		String inputCity = 'Stuttgart';
		String inputCountry = 'DE';
		
		
		// Exercise
		Id resultLocationId = LocationFinder.findLocation(inputCity,inputCountry);
		
		
		
		// Verify
		System.assertEquals(existingLocation1.id, resultLocationId);
	}
	
	
	@isTest
	private static void succeedsWhenRemainderLocationIsReturnedForMultipleSameCountryLocations() {
		// Setup
		CompensationRate__c existingLocation1 = insertLocation('Deutschland(Stuttgart)', 'Deutschland','Stuttgart', 'DE');
		CompensationRate__c existingLocation2 = insertLocation('Deutschland(Other)', 'Deutschland', 'Other', 'DE');
		CompensationRate__c existingLocation3 = insertLocation('Afghanistan', 'Afghanistan', null, 'AF');
		
		String inputCity = 'M?nchen';
		String inputCountry = 'DE';
		
		
		// Exercise
		Id resultLocationId = LocationFinder.findLocation(inputCity,inputCountry);
		
		
		
		//Verify
		System.assertEquals(existingLocation2.id, resultLocationId);
	}
	
	
	@isTest
	private static void succeedsWhenNoLocationIsReturned() {
		// Setup
		CompensationRate__c existingLocation1 = insertLocation('Deutschland(Stuttgart)', 'Deutschland','Stuttgart', 'DE');
		CompensationRate__c existingLocation2 = insertLocation('Deutschland(Other)', 'Deutschland', 'Other', 'DE');
		CompensationRate__c existingLocation3 = insertLocation('Afghanistan', 'Afghanistan', null, 'AF');
		CompensationRate__c existingLocation4 = insertLocation('Frankreich', 'Frankreich', null, 'FA');
		
		String inputCity = 'Rom';
		String inputCountry = 'IT';
		
		
		// Exercise
		Id resultLocationId = LocationFinder.findLocation(inputCity,inputCountry);
		
		
		// Verify
		System.assertEquals(null, resultLocationId);
	}
	
	
	// TEST HELPER
	private static CompensationRate__c insertLocation(String name, String country, String city,  String countryCode) {
		CompensationRate__c result = new CompensationRate__c(Name = name,
                                                             txt_CountryName__c = country,	
                                                             txt_CityName__c = city,
															 txt_CountryCode__c = countryCode,
															 cur_FullDailyRate__c =50,
															 cur_PartialDailyRate__c =25,
															 cur_OvernightStayRate__c =60);
		insert result;
		
		return result;
	}  
}