src/objects/CompensationRate__c.object
<CustomObject>
    <description>Various rates to reimburse dependant expense types e.g. travels with private vehicles etc.</description>
    <fields>
        <fullName>txt_CityName__c</fullName>
        <inlineHelpText>Only enter a city if there are special rates for this specific city.</inlineHelpText>
        <label>City Name (optional)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>txt_CountryCode__c</fullName>
        <description>The Country Code of the Country using the ISO 3166-1 alpha-2 Code.</description>
        <inlineHelpText>Enter the &quot;ISO 2 Letter Country Code&quot; for this country.</inlineHelpText>
        <label>Country Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Compensation Rate</label>
    <nameField>
        <label>Compensation Rate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compensation Rates</pluralLabel>
    <recordTypes>
        <fullName>Location</fullName>
        <active>true</active>
        <description>Daily rates for calculating per Diem compensation</description>
        <label>Location</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LocationFinder.cls
public with sharing class LocationFinder {
	
	
	// PUBLIC METHODS
	
	public static Id findLocation(String city, String country) {
		Id result;
		
		CompensationRate__c location = getLocation(country, city);
		
		if(location != null) {
			result = location.Id;
		}
		
		return result;
	}
	
	
	// PRIVATE METHODS
	
	private static CompensationRate__c getLocation(String countryCode, String city) {
		CompensationRate__c result;
		
		Id location = CompensationRateType.getLocationId();
		
		for(CompensationRate__c rate : [SELECT Id
				  						FROM CompensationRate__c
				  						WHERE RecordTypeId = :location
									    AND txt_CityName__c = null
									    AND txt_CountryCode__c = :countryCode LIMIT 1]) {
	    	result = rate;
	    }
		
		if(result == null) {
			for(CompensationRate__c rate : [SELECT Id
									  	    FROM CompensationRate__c 
										    WHERE RecordTypeId = :location
										    AND txt_CountryCode__c = :countryCode 
										    AND txt_CityName__c = :city LIMIT 1]) {
		    	result = rate;
		    }
		}
		
		if(result == null) {
			for(CompensationRate__c rate : [SELECT Id
										    FROM CompensationRate__c 
										    WHERE RecordTypeId = :location
										    AND txt_CountryCode__c = :countryCode 
										    AND txt_CityName__c = 'Other' LIMIT 1]) {
		    	result = rate;
		    }															
		}
			
		return result;
	}
}