src/objects/Expense__c.object
<CustomObject>
    <description>Contains informations about the expenses.</description>
    <fields>
        <fullName>dtm_ArrivalTime__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_DepartureTime__c</fullName>
        <label>Departure Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>mdr_Travel__c</fullName>
        <label>Travel</label>
        <referenceTo>Travel__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Expense #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <description>Expense for airtravel</description>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LongDistanceRide__c.object
<CustomObject>
    <fields>
        <fullName>dtm_ArrivalTime__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_DepartureTime__c</fullName>
        <label>Departure Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>mdr_RentalVehicle__c</fullName>
        <label>Rental Vehicle</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This is not a Rental Vehicle expense.</errorMessage>
            <filterItems>
                <field>Expense__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Rental Vehicle</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Long Distance Rides</relationshipLabel>
        <relationshipName>Long_Distance_Rides</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Long Distance Ride</label>
    <nameField>
        <displayFormat>LDR-{0000}</displayFormat>
        <label>Long Distance Ride #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Long Distance Rides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ExpensesDontOverlap.cls
public with sharing class ExpensesDontOverlap implements ExpenseRule {

    
    // PUBLIC METHODS
    
    public void validate(List<SObject> records) {
    	List<Expense__c> expenses = (List<Expense__c>) records;
    	String errorMessage = 'Expense overlaps with an existing movement( flight, train ride, private or company vehicle ride, rental vehicle ride).';
    	// Possible problem because inserted Expenses are not taken into account for other expenses.

    	Map<Id,List<Expense__c>> expensesByTravels = queryRelevantExpensesByTravel(expenses);
    	
    	for(Expense__c expense : expenses) {
    		
	        if(ExpenseType.isMovement(expense)) {
	        	List<Expense__c> movementExpenses = expensesByTravels.get(expense.mdr_Travel__c);
		        
		        for(Expense__c existing : movementExpenses) {
		        	
		        	if(doOverlap(expense, existing)) {
		        		
		        		if(existing.Id == null) {
		        			expense.addError(errorMessage);
		        					        		
		        			break;
		        		}
		        		else if(existing.Id != expense.Id) {
		        			expense.addError(errorMessage);
		        		
		        			break;		        			
		        		}
		        	}
		        }
	        }
    	}
    }
    
    
    // PRIVATE METHODS
    
    private Map<Id, List<Expense__c>> queryRelevantExpensesByTravel(List<Expense__c> expenses) {
    	Map<Id, List<Expense__c>> resultMap = new Map<Id, List<Expense__c>>();
    	
    	Set<Id> movementRecordTypes = ExpenseType.getMovementRecordTypeIds();
		movementRecordTypes.add(ExpenseType.getRentalVehicleRecordTypeId());
		
		for(Expense__c incomingExpense : expenses) {
			Id travel = incomingExpense.mdr_Travel__c;
			
			if( !resultMap.containsKey(travel)) {
				resultMap.put(travel, new List<Expense__c>());
			}
		}
		
		for(Expense__c expense : [SELECT Id, RecordTypeId, mdr_Travel__c, dtm_DepartureTime__c, dtm_ArrivalTime__c, 
									(SELECT dtm_DepartureTime__c, dtm_ArrivalTime__c 
 		  	 						 FROM Long_Distance_Rides__r)
						    	  FROM Expense__c 
						    	  WHERE RecordTypeId IN :movementRecordTypes 
						    	  AND mdr_Travel__c IN :resultMap.keySet()]) {
			
			List<Expense__c> movementExpenses = resultMap.get(expense.mdr_Travel__c);
			
			if(ExpenseType.isRentalVehicle(expense)) {
				for(LongDistanceRide__c ride : expense.Long_Distance_Rides__r) {
					
					Expense__c falseExpense = new Expense__c();
		    		falseExpense.dtm_DepartureTime__c = ride.dtm_DepartureTime__c;
		    		falseExpense.dtm_ArrivalTime__c = ride.dtm_ArrivalTime__c;
		    		
					movementExpenses.add(falseExpense);
				}
			}
			else {
				movementExpenses.add(expense);
			}	
		}
    	
    	return resultMap;
    }
    
    
    private Boolean doOverlap( Expense__c expense, Expense__c existing) {
        Boolean noOverlap = ( existing.dtm_ArrivalTime__c < expense.dtm_DepartureTime__c
        				 	|| existing.dtm_DepartureTime__c > expense.dtm_ArrivalTime__c );

        return !noOverlap;
    }
}