src/objects/Expense__c.object
<CustomObject>
    <description>Contains informations about the expenses.</description>
    <fields>
        <fullName>lkp_LocationFrom__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location From</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a location.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Expenses (Location From)</relationshipLabel>
        <relationshipName>Expenses2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>lkp_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a location.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>txt_From__c</fullName>
        <inlineHelpText>Please use the autocomplete to choose the location.</inlineHelpText>
        <label>From</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>txt_LodgingAdress__c</fullName>
        <inlineHelpText>Please use the autocomplete to choose the location.</inlineHelpText>
        <label>Lodging Adress</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>txt_PlaceOfEntertainment__c</fullName>
        <inlineHelpText>Please use the autocomplete to choose the location.</inlineHelpText>
        <label>Place Of Entertainment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>txt_To__c</fullName>
        <inlineHelpText>Please use the autocomplete to choose the location.</inlineHelpText>
        <label>To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Expense #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ExpenseHasValidLocation.cls
public with sharing class ExpenseHasValidLocation implements ExpenseRule{
	    
    
    public void validate(List<SObject> records) {
    	String errorMessage = 'Unknown location, please choose a location from the autocomplete drop-down list.';

    	for(Expense__c expense : (List<Expense__c>)records) {
			
	    	if(ExpenseType.isMovement(expense)) {
	    		if(expense.lkp_Location__c == null) {
		    		expense.txt_To__c.addError(errorMessage);
	    		}
		 		if(expense.lkp_LocationFrom__c == null) {
					expense.txt_From__c.addError(errorMessage);
				}
	    	}
	    	else if(ExpenseType.isAccommodation(expense) && expense.lkp_Location__c == null) {
				expense.txt_LodgingAdress__c.addError(errorMessage);
	    	}
	    	else if(ExpenseType.isEntertainment(expense) && expense.lkp_Location__c == null) {
				expense.txt_PlaceOfEntertainment__c.addError(errorMessage);
	    	}
    	}
    }
}