src/objects/Expense__c.object
<CustomObject>
    <description>Contains informations about the expenses.</description>
    <fields>
        <fullName>chk_RoundTrip__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RoundTrip</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>cur_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Overall cost of the expense.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>cur_Bill__c</fullName>
        <label>Bill</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>cur_Tip__c</fullName>
        <label>Tip</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>dat_CheckOutDate__c</fullName>
        <label>Check Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dat_ExpenseDate__c</fullName>
        <description>To assign a Expense to a specific travel date.</description>
        <label>Expense Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dat_ReturnDate__c</fullName>
        <label>Return Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dtm_ArrivalTime__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_DepartureTime__c</fullName>
        <label>Departure Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_End__c</fullName>
        <label>End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_ReturnArrival__c</fullName>
        <label>Return Arrival</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_ReturnDeparture__c</fullName>
        <label>Return Departure</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>fcur_MilageCosts__c</fullName>
        <formula>lkp_VehicleType__r.cur_MilageAllowance__c  *  num_Milage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Milage Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>lkp_LocationFrom__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location From</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a location.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Expenses (Location From)</relationshipLabel>
        <relationshipName>Expenses2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>lkp_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a location.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>lkp_ReturnTrip__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Return Trip</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>mdr_Travel__c</fullName>
        <label>Travel</label>
        <referenceTo>Travel__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>pkl_Reimbursement__c</fullName>
        <label>Reimbursement</label>
        <picklist>
            <picklistValues>
                <fullName>I paid for this, please reimburse me.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The company paid for this.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>The customer paid for this.</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>txa_Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>txt_From__c</fullName>
        <inlineHelpText>Please use the autocomplete to choose the location.</inlineHelpText>
        <label>From</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>txt_Reason__c</fullName>
        <label>Reason</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>txt_To__c</fullName>
        <inlineHelpText>Please use the autocomplete to choose the location.</inlineHelpText>
        <label>To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Expense #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Travel__c.object
<CustomObject>
    <description>Records of business travels.</description>
    <fields>
        <fullName>dtm_End__c</fullName>
        <label>End</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_Start__c</fullName>
        <label>Start</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>fcur_Reimbursement__c</fullName>
        <formula>rsum_ReimbursableExpenses__c  +  rsum_PerDiems__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Reimbursement</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>rsum_PerDiems__c</fullName>
        <label>Total per Diems</label>
        <summarizedField>Expense__c.cur_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Expense__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>per Diem</value>
        </summaryFilterItems>
        <summaryForeignKey>Expense__c.mdr_Travel__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>rsum_ReimbursableExpenses__c</fullName>
        <label>Reimbursable Expenses</label>
        <summarizedField>Expense__c.cur_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Expense__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Flight, Accommodation, Train Ride, Private Vehicle Ride, Miscellaneous, Sea Travel, Entertainment, Rental Vehicle, Company Vehicle Ride</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Expense__c.pkl_Reimbursement__c</field>
            <operation>equals</operation>
            <value>&quot;I paid for this, please reimburse me.&quot;</value>
        </summaryFilterItems>
        <summaryForeignKey>Expense__c.mdr_Travel__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>rsum_TotalExpenses__c</fullName>
        <label>Total Expenses</label>
        <summarizedField>Expense__c.cur_Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Expense__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Flight, Accommodation, Train Ride, Private Vehicle Ride, Miscellaneous, Sea Travel, Entertainment, Rental Vehicle, Company Vehicle Ride</value>
        </summaryFilterItems>
        <summaryForeignKey>Expense__c.mdr_Travel__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>txa_Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>txt_Reason__c</fullName>
        <label>Reason</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Travel</label>
    <nameField>
        <label>Travel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ExpensesTriggerHandler.cls
public with sharing class ExpensesTriggerHandler extends AbstractTriggerHandler{
	
	private List<Expense__c> newExpenses;
	private List<Expense__c> oldExpenses;
	
	private RuleValidator validator;
		
	
	//CONSTRUCTOR
	
	public ExpensesTriggerHandler() {
		newExpenses = filterOutPerDiems(Trigger.new);
		oldExpenses = filterOutPerDiems(Trigger.old);
		
		validator = new RuleValidator(RuleType.ExpenseRule);
	}
	
	
	// PUBLIC METHODS
	
	public override void onBeforeInsert() {
		validator.validate(newExpenses);	
			
		populateFields(newExpenses);
		
		createReturnTripExpenses(newExpenses);
	}
	
	
	public override void onBeforeUpdate() {
		validator.validate(newExpenses);		
		
		populateFields(newExpenses);
		
		deleteReturnTripExpenses(oldExpenses);
		createReturnTripExpenses(newExpenses);
	}
	
	
	public override void onBeforeDelete() {
		deleteReturnTripExpenses(oldExpenses);
	}
	
	
	public override void onAfterInsert() {
		calculatePerDiems(newExpenses);
	}
	
	
	public override void onAfterUpdate() {
		calculatePerDiems(newExpenses);
	}
	
	
	public override void onAfterDelete() {
		calculatePerDiems(oldExpenses);
	}
			
	
	// PRIVATE METHODS
	
	private List<Expense__c> filterOutPerDiems(List<SObject> expenses) {
		List<Expense__c> results = new List<Expense__c>();
		
		if(expenses != null && !expenses.isEmpty()) {
			for(Expense__c e : (List<Expense__c>) expenses) {
				if(!ExpenseType.isPerDiem(e)) {
					results.add(e);
				}
			}
		}
		
		return results;
	}
	
	
	private void calculatePerDiems(List<Expense__c> expenses) {
		Set<Id> expenseIds = new Set<Id>();
		for(Expense__c e : expenses) {
			expenseIds.add(e.mdr_Travel__c);
		}
		
		List<Travel__c> allAffectedTravels = [SELECT Id, Name, CurrencyIsoCode, txt_Reason__c, txa_Description__c, 
                         							 dtm_Start__c, dtm_End__c, Owner.FirstName, Owner.LastName, 
                         							 rsum_TotalExpenses__c, rsum_ReimbursableExpenses__c, rsum_PerDiems__c, 
                         							 fcur_Reimbursement__c
											  FROM Travel__c 
											  WHERE Id IN :expenseIds];
		
		for(Travel__c t : allAffectedTravels) {
			PerDiemCalculator perDiemCalculator = new PerDiemCalculator(t);
        	perDiemCalculator.calculate();
		}
	}
	
	
	private void populateFields(List<Expense__c> expenses) {
		for(Expense__c expense : expenses) {
			populateExpenseDate(expense);
			populateAmount(expense);
			populateReimbursement(expense);
		}		
	}


	private void populateExpenseDate(Expense__c expense) {
		if(ExpenseType.isMovement(expense)) {
			expense.dat_ExpenseDate__c = expense.dtm_DepartureTime__c.date();
		}
		else if(ExpenseType.isAccommodation(expense)) {
			expense.dat_ExpenseDate__c = expense.dat_CheckOutDate__c;
		}
		else if(ExpenseType.isRentalVehicle(expense)) {
			expense.dat_ExpenseDate__c = expense.dat_ReturnDate__c;
		}
	}
	
	
	private void populateAmount(Expense__c expense) {
		if(ExpenseType.isPrivateVehicle(expense)) {			
			expense.cur_Amount__c = expense.fcur_MilageCosts__c;
		}
		else if(ExpenseType.isEntertainment(expense)) {
			expense.cur_Amount__c = expense.cur_Bill__c + expense.cur_Tip__c;
		}
	}
	
	
	private void populateReimbursement(Expense__c expense) {
		if(ExpenseType.isPrivateVehicle(expense)) {			
			expense.pkl_Reimbursement__c = 'I paid for this, please reimburse me.';
		}
		else if(ExpenseType.isCompanyVehicle(expense)) {			
			expense.pkl_Reimbursement__c = 'The company paid for this.';
		}
	}
	
	
	private void createReturnTripExpenses(List<Expense__c> expenses) {
		for(Expense__c expense : expenses) {
			if(ExpenseType.isMovement(expense) && expense.chk_RoundTrip__c) {
				Expense__c returnTrip = new Expense__c();
				
				returnTrip.RecordTypeId = expense.RecordTypeId;
				returnTrip.cur_Amount__c = 0;
				returnTrip.lkp_LocationFrom__c = expense.lkp_Location__c;
				returnTrip.lkp_Location__c = expense.lkp_LocationFrom__c;
				returnTrip.pkl_Reimbursement__c = expense.pkl_Reimbursement__c;
				returnTrip.mdr_Travel__c = expense.mdr_Travel__c;
				returnTrip.chk_RoundTrip__c = false;
				returnTrip.dtm_DepartureTime__c = expense.dtm_ReturnDeparture__c;
				returnTrip.dtm_ArrivalTime__c = expense.dtm_ReturnArrival__c;
				returnTrip.txt_From__c = expense.txt_To__c;
				returnTrip.txt_To__c = expense.txt_From__c;
                returnTrip.dat_ExpenseDate__c = expense.dtm_ArrivalTime__c.date();
				
				try {
					insert returnTrip;	
					expense.lkp_ReturnTrip__c = returnTrip.Id;
				}
				catch(DMLException e) {
					expense.addError(e.getDMLMessage(0));
				}
			}
		}		
	}
	
	
	private void deleteReturnTripExpenses(List<Expense__c> expenses) {
		Set<Id> returnTripExpenseIds = new Set<Id>();
		
		for(Expense__c expense : expenses) {
			if(ExpenseType.isMovement(expense) && expense.chk_RoundTrip__c) {
				returnTripExpenseIds.add(expense.lkp_ReturnTrip__c);
			}
		}
		
		List<Expense__c> returnTripExpenses = [SELECT Id 
											   FROM Expense__c 
											   WHERE Id IN :returnTripExpenseIds];
									           						  
		delete returnTripExpenses;
	}							           						  
}