src/objects/Expense__c.object
<CustomObject>
    <description>Contains informations about the expenses.</description>
    <fields>
        <fullName>dat_CheckInDate__c</fullName>
        <label>Check In Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dat_CheckOutDate__c</fullName>
        <label>Check Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dat_PickUpDate__c</fullName>
        <label>Pick-up Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dat_ReturnDate__c</fullName>
        <label>Return Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dtm_ArrivalTime__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_DepartureTime__c</fullName>
        <label>Departure Time</label>
        <type>DateTime</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Expense #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ExpenseCannotEndBeforeStart.cls
public with sharing class ExpenseCannotEndBeforeStart implements ExpenseRule {
    
 
 	// PUBLIC METHODS
 	
    public void validate(List<SObject> records) {
    	String errorMessage = 'Expense cannot end before it started.';

    	for(Expense__c expense : (List<Expense__c>)records) {
    		
	        if (ExpenseType.isMovement(expense) && expense.dtm_ArrivalTime__c <= expense.dtm_DepartureTime__c) {
	        	expense.dtm_ArrivalTime__c.addError(errorMessage);
	        }
	        else if(ExpenseType.isAccommodation(expense) && expense.dat_CheckOutDate__c <= expense.dat_CheckInDate__c) {
		    	expense.dat_CheckOutDate__c.addError(errorMessage);
	        }
	        else if (ExpenseType.isRentalVehicle(expense) && expense.dat_ReturnDate__c < expense.dat_PickUpDate__c) {
	        	expense.dat_ReturnDate__c.addError(errorMessage);
	        }
    	}
    }
}