src/objects/Expense__c.object
<CustomObject>
    <description>Contains informations about the expenses.</description>
    <fields>
        <fullName>dat_PickUpDate__c</fullName>
        <label>Pick-up Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dat_ReturnDate__c</fullName>
        <label>Return Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>dtm_ArrivalTime__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_DepartureTime__c</fullName>
        <label>Departure Time</label>
        <type>DateTime</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Expense #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <recordTypes>
        <fullName>RentalVehicle</fullName>
        <active>true</active>
        <description>Expense for renting a vehicle.</description>
        <label>Rental Vehicle</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LongDistanceRide__c.object
<CustomObject>
    <fields>
        <fullName>dtm_ArrivalTime__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_DepartureTime__c</fullName>
        <label>Departure Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>mdr_RentalVehicle__c</fullName>
        <label>Rental Vehicle</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This is not a Rental Vehicle expense.</errorMessage>
            <filterItems>
                <field>Expense__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Rental Vehicle</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Long Distance Rides</relationshipLabel>
        <relationshipName>Long_Distance_Rides</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Long Distance Ride</label>
    <nameField>
        <displayFormat>LDR-{0000}</displayFormat>
        <label>Long Distance Ride #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Long Distance Rides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LongDistanceRideCannotBeOutsideOfRental.cls
public class LongDistanceRideCannotBeOutsideOfRental implements LongDistanceRideRule {


	// PUBLIC METHODS
	
	public void validate(List<SObject> records) {
		List<LongDistanceRide__c> rides = (List<LongDistanceRide__c>) records;
		String errorMessage = 'The Long Distance Ride cannot be outside of the rental period.';
		
		Map<Id,Expense__c> relevantRentalVehicles = queryRelevantRentalCarsById(rides);
		
		for(LongDistanceRide__c ride : rides) {
			Expense__c rentalVehicle = relevantRentalVehicles.get(ride.mdr_RentalVehicle__c);
			
			if(isOutsideOfRental(ride.dtm_DepartureTime__c, rentalVehicle)) {
				ride.dtm_DepartureTime__c.addError(errorMessage);
			}
			if(isOutsideOfRental(ride.dtm_ArrivalTime__c, rentalVehicle)) {
				ride.dtm_ArrivalTime__c.addError(errorMessage);
			}
		}
	}
	
	
	// PRIVATE METHODS
	
	private Map<Id,Expense__c> queryRelevantRentalCarsById(List<LongDistanceRide__c> rides) {
		Set<Id> rentalVehicles = new Set<Id>();
		
		for(LongDistanceRide__c ride : rides){
			rentalVehicles.add(ride.mdr_RentalVehicle__c);
		}
		
		Map<Id,Expense__c> resultMap = new Map<Id,Expense__c>([SELECT dat_PickUpDate__c, dat_ReturnDate__c
															   FROM Expense__c
															   WHERE Id IN :rentalVehicles]);
															   
	   return resultMap;
	}
	
	
	private Boolean isOutsideOfRental(DateTime dtm, Expense__c e) {
    	Boolean result = dtm.date() < e.dat_PickUpDate__c || dtm.date() > e.dat_ReturnDate__c;
    	
    	return result;
    }
}