src/objects/Expense__c.object
<CustomObject>
    <description>Contains informations about the expenses.</description>
    <fields>
        <fullName>chk_RoundTrip__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RoundTrip</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>dtm_ReturnArrival__c</fullName>
        <label>Return Arrival</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_ReturnDeparture__c</fullName>
        <label>Return Departure</label>
        <type>DateTime</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Expense #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ExpenseNeedsReturnInformationIfRoundTrip.cls
public with sharing class ExpenseNeedsReturnInformationIfRoundTrip  implements ExpenseRule {
 
 	// PUBLIC METHODS
 	
    public void validate(List<SObject> records) {

    	for(Expense__c expense : (List<Expense__c>)records) {
	        if ( expense.chk_RoundTrip__c ) {
	        	if( expense.dtm_ReturnDeparture__c == null ) {
	        		expense.dtm_ReturnDeparture__c.addError('Return departure time is missing');
	        	}
	        	if( expense.dtm_ReturnArrival__c == null ) {
	        		expense.dtm_ReturnArrival__c.addError('Return arrival time is missing.');
	        	}
	        }
    	}
    }
}