src/objects/LongDistanceRide__c.object
<CustomObject>
    <fields>
        <fullName>lkp_LocationFrom__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location From</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This is not a Location.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Long Distance Rides</relationshipLabel>
        <relationshipName>Long_Distance_Rides</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>lkp_LocationTo__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Location To</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This is not a Location.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Location</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Long Distance Rides (Location To)</relationshipLabel>
        <relationshipName>Long_Distance_Rides1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>txt_From__c</fullName>
        <label>From</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>txt_To__c</fullName>
        <label>To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Long Distance Ride</label>
    <nameField>
        <displayFormat>LDR-{0000}</displayFormat>
        <label>Long Distance Ride #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Long Distance Rides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RideHasValidLocation.cls
public with sharing class RideHasValidLocation implements LongDistanceRideRule {
	
	
	public void validate(List<SObject> records) {
		String errorMessage = 'Unknown location, please choose a location from the autocomplete drop-down list.';
		
    	for(LongDistanceRide__c ride : (List<LongDistanceRide__c>) records) {
    		
			if(ride.lkp_LocationFrom__c == null) {
				ride.txt_From__c.addError(errorMessage);
			}
			if(ride.lkp_LocationTo__c == null) {
				ride.txt_To__c.addError(errorMessage);
			}
    	}
    }
}