src/objects/LongDistanceRide__c.object
<CustomObject>
    <fields>
        <fullName>chk_RoundTrip__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Round Trip</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>dtm_ReturnArrival__c</fullName>
        <label>Return Arrival</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_ReturnDeparture__c</fullName>
        <label>Return Departure</label>
        <type>DateTime</type>
    </fields>
    <label>Long Distance Ride</label>
    <nameField>
        <displayFormat>LDR-{0000}</displayFormat>
        <label>Long Distance Ride #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Long Distance Rides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RideNeedsReturnInfoWhenRoundTripChecked.cls
public with sharing class RideNeedsReturnInfoWhenRoundTripChecked implements LongDistanceRideRule{
    
    
    // PUBLIC METHODS
    
    public void validate(List<SObject> records) {
        for(LongDistanceRide__c ride : (List<LongDistanceRide__c>)records) {
        	
            if (ride.chk_RoundTrip__c) {
                if(ride.dtm_ReturnDeparture__c == null) {
                    ride.dtm_ReturnDeparture__c.addError('Return departure time is missing');
                }
                if(ride.dtm_ReturnArrival__c == null) {
                    ride.dtm_ReturnArrival__c.addError('Return arrival time is missing.');
                }
            }
        }
    }
}