src/objects/LongDistanceRide__c.object
<CustomObject>
    <fields>
        <fullName>dtm_ArrivalTime__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_DepartureTime__c</fullName>
        <label>Departure Time</label>
        <type>DateTime</type>
    </fields>
    <label>Long Distance Ride</label>
    <nameField>
        <displayFormat>LDR-{0000}</displayFormat>
        <label>Long Distance Ride #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Long Distance Rides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LongDistanceRideCannotEndBeforeStart.cls
public with sharing class LongDistanceRideCannotEndBeforeStart implements LongDistanceRideRule {
	
	
	// PUBLIC METHODS
	 
    public void validate(List<SObject> records) {
    	for(LongDistanceRide__c ldr : (List<LongDistanceRide__c>) records) {
    		
	        if (ldr.dtm_ArrivalTime__c <= ldr.dtm_DepartureTime__c) {
	        	ldr.dtm_ArrivalTime__c.addError('Long Distance Ride cannot end before it started.');
	        }
    	}
    }
}