src/objects/MealInvitation__c.object
<CustomObject>
    <fields>
        <fullName>dat_Day__c</fullName>
        <label>Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>lkp_Breakfast__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Breakfast</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a Meal.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Meal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Meal Invitations</relationshipLabel>
        <relationshipName>Meal_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>lkp_Dinner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Dinner</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a meal.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Meal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Meal Invitations (Dinner)</relationshipLabel>
        <relationshipName>Meal_Invitations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>lkp_Lunch__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Lunch</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Not a meal.</errorMessage>
            <filterItems>
                <field>CompensationRate__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Meal</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CompensationRate__c</referenceTo>
        <relationshipLabel>Meal Invitations (Lunch)</relationshipLabel>
        <relationshipName>Meal_Invitations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>mdr_Travel__c</fullName>
        <label>Travel</label>
        <referenceTo>Travel__c</referenceTo>
        <relationshipLabel>Meal Invitations</relationshipLabel>
        <relationshipName>MealInvitations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Meal Invitation</label>
    <nameField>
        <displayFormat>MI-{0000}</displayFormat>
        <label>Meal Invitation #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meal Invitations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Travel__c.object
<CustomObject>
    <description>Records of business travels.</description>
    <label>Travel</label>
    <nameField>
        <label>Travel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MealInvitationsTriggerHandler_Test.cls
@isTest
private class MealInvitationsTriggerHandler_Test {
	
	static {
		CustomSettings.addDefault();
	}

	private static final Date DAY_TODAY = System.today();
	private static final Date DAY_TOMORROW = DAY_TODAY.addDays(1);
	private static final DateTime TODAY_NOW = System.now();
	private static final DateTime TOMORROW_NOW = TODAY_NOW.addDays(1);
	
	
	@isTest
	private static void succeedsWhenNoMealInvitationOutOfTravel() {
		// Setup
		Exception expectedException;
		String expectedMessage = 'The date has to be within the travel period.';
		
		
		// Exercise
		try {
			Travel__c travel = new TravelBuilder(TODAY_NOW,TOMORROW_NOW)
										.addMealInvitation(DAY_TODAY.addDays(-1),false,false,true)
										.addMealInvitation(DAY_TOMORROW.addDays(1),true,true,false)
										.create();
		}
		catch(DMLException e) {
			expectedException = e;
		}
									
		
		// Verify
		System.assertNotEquals(null,expectedException);
		assertThrowsMessage(expectedMessage);
	}
	
	
	@isTest
	private static void succeedsWhenNoDuplicateDatesInSameTravel() {
		// Setup
		Exception expectedException;
		String expectedMessage = 'There already exists a meal invitation for this date.';
		
		
		// Exercise
		try {
			Travel__c travel = new TravelBuilder(TODAY_NOW,TOMORROW_NOW)
										.addMealInvitation(DAY_TODAY,false,false,true)
										.addMealInvitation(DAY_TODAY,true,true,false)
										.create();
		}
		catch(DMLException e) {
			expectedException = e;
		}
									
		
		// Verify
		System.assertNotEquals(null,expectedException);
		assertThrowsMessage(expectedMessage);
	}
	
	
	@isTest
	private static void succeedsWhenMealInvitationHasCorrectLookups() {
		// Setup
		Exception unexpectedException;
		String message = '';
		
		Travel__c travel;
		
		
		// Exercise
		try {
			travel = new TravelBuilder(TODAY_NOW, TOMORROW_NOW)
										.addMealInvitation(DAY_TODAY, true, true, true)
										.addMealInvitation(DAY_TOMORROW, false, false, false)
										.create();
		}
		catch(DMLException e) {
			unexpectedException = e;
			message = unexpectedException.getStackTraceString();
		}
									
		
		// Verify
		System.assertEquals(null, unexpectedException, message);
		assertAllFieldsHaveLookups(travel, DAY_TODAY);
		assertNoFieldsHaveLookups(travel, DAY_TOMORROW);
	}
	
	
	// TEST HELPER
	private static void assertThrowsMessage(String errorMessage) {
		Boolean result = false;
		
		for(ApexPages.Message m : ApexPages.getMessages()) {
			if(m.getDetail().equals(errorMessage)) {
				result = true;
			}
		}
		
		System.assert(result);
	}
	
	
	private static void assertAllFieldsHaveLookups(Travel__c travel, Date day) {
		MealInvitation__c meal = [SELECT Id, lkp_Breakfast__c, lkp_Lunch__c, lkp_Dinner__c, dat_Day__c, mdr_Travel__c
								  FROM MealInvitation__c
								  WHERE mdr_Travel__c = :travel.Id
								  AND dat_Day__c = :day];
		
		System.assertNotEquals(null, meal.lkp_Breakfast__c);
		System.assertNotEquals(null, meal.lkp_Lunch__c);
		System.assertNotEquals(null, meal.lkp_Dinner__c);
	}
	
	
	private static void assertNoFieldsHaveLookups(Travel__c travel, Date day) {
		MealInvitation__c meal = [SELECT Id,lkp_Breakfast__c,lkp_Lunch__c,lkp_Dinner__c,dat_Day__c,mdr_Travel__c
								  FROM MealInvitation__c
								  WHERE mdr_Travel__c = :travel.Id
								  AND dat_Day__c = :day];
		
		System.assertEquals(null, meal.lkp_Breakfast__c);
		System.assertEquals(null, meal.lkp_Lunch__c);
		System.assertEquals(null, meal.lkp_Dinner__c);
	}
}