src/objects/MealInvitation__c.object
<CustomObject>
    <fields>
        <fullName>dat_Day__c</fullName>
        <label>Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>mdr_Travel__c</fullName>
        <label>Travel</label>
        <referenceTo>Travel__c</referenceTo>
        <relationshipLabel>Meal Invitations</relationshipLabel>
        <relationshipName>MealInvitations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Meal Invitation</label>
    <nameField>
        <displayFormat>MI-{0000}</displayFormat>
        <label>Meal Invitation #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meal Invitations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Travel__c.object
<CustomObject>
    <description>Records of business travels.</description>
    <fields>
        <fullName>dtm_End__c</fullName>
        <label>End</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>dtm_Start__c</fullName>
        <label>Start</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>Travel</label>
    <nameField>
        <label>Travel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Travels</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MealInvitationCannotBeOutOfTravelPeriod.cls
public class MealInvitationCannotBeOutOfTravelPeriod implements MealInvitationRule {
	
	
	// PUBLIC METHODS
	
	public void validate(List<SObject> records) {
		List<MealInvitation__c> mealInvitations = (List<MealInvitation__c>) records;

		Map<Id,Travel__c> travels = queryTravels(mealInvitations);
		
		for( MealInvitation__c invitation :  mealInvitations) {
			Travel__c travel = travels.get(invitation.mdr_Travel__c);
			
			if(isOutOfTravel(invitation.dat_Day__c,travel)) {
				invitation.dat_Day__c.addError('The date has to be within the travel period.');
			}
		}
	}
	
	
	// PRIVATE METHODS
	
	private Map<Id,Travel__c> queryTravels(List<MealInvitation__c> invitations) {
		Set<Id> relevantTravels = new Set<Id>();
		
		for(MealInvitation__c invitation : invitations) {
			relevantTravels.add(invitation.mdr_Travel__c);
		}
		
		Map<Id,Travel__c> resultMap = new Map<Id,Travel__c>([SELECT dtm_Start__c, dtm_End__c
										   					 FROM Travel__c
										   					 WHERE Id IN :relevantTravels]);
										   	
		return resultMap;
	}
	
	
	private Boolean isOutOfTravel(Date day, Travel__c travel) {
		Boolean result = (day < travel.dtm_Start__c.date()) || (day > travel.dtm_End__c.date());
		
		return result;
	}
}